apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: podinfo
spec:
  scaleTargetRef:
    name: podinfo
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
  - type: cpu
    metadata:
      metricType: Utilization
      value: "50"
