apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo-keda
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: "6.4.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    hpa:
      enabled: false
    # Add label so we can identify this deployment
    podLabels:
      scaled-object: "true"
