apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo-keda
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: "6.4.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    hpa:
      enabled: false
    podLabels:
      scaled-object: "true"
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: keda.sh/v1alpha1
              kind: ScaledObject
              metadata:
                name: podinfo-keda
                namespace: default
              spec:
                scaleTargetRef:
                  name: podinfo-keda
                  kind: Deployment
                  apiVersion: apps/v1
                minReplicaCount: 2
                maxReplicaCount: 4
                triggers:
                - type: cpu
                  metricType: Utilization
                  metadata:
                    value: "50"
            target:
              kind: Deployment
              name: podinfo-keda
