apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: podinfo-keda
  namespace: default
spec:
  scaleTargetRef:
    name: podinfo-keda
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
